#!/bin/sh

PID_PATH=/var/run/sine1k.PID

do_play () {
  if [ -n "$1" ]; then
    wav_path="$1"
  else
    wav_path=/1KHz_192KHz_24bit_60sec_0db.wav
  fi
  [ -e "$wav_path" ] || exit 2
  while true; do
    aplay $wav_path &>/dev/null
  done
}

case "$1" in
"start")
  shift
  amixer sset Master 50
  do_play $* &
  echo "$!" > $PID_PATH
  ;;
"stop")
  if [ -e "$PID_PATH" ]; then
    cat $PID_PATH | while read pid; do
      kill $pid
    done
    rm $PID_PATH
    killall aplay
  fi
  ;;
*)
  cat <<-EOHERE
USAGE
    `basename $0` [start|stop]

OPTIONS
    start  Start service
    stop   Stop service

EOHERE
  ;;
esac






