#!/bin/sh

. /etc/init.d/func

_pri_tag="sshd-initd"

log_d "$0 $*"

_pri_daemin_exec="/sbin/sshd"
_pri_daemin_pid="/var/run/sshd.pid"

sshd_start () {

  # fix message: Privilege separation user sshd does not exist
  id sshd >/dev/null 2>&1 || adduser sshd -DH -s /usr/sbin/nologin

  # fix message: must be owned by root and not group or world-writable.
  _lo_emptydir=/var/empty
  [ -d "${_lo_emptydir}" ] || mkdir -p ${_lo_emptydir} || { log_e "failed"; return 1; }

  if ! find_mount "*" ${_lo_emptydir} >/dev/null; then
    cmd_run mount -t tmpfs none ${_lo_emptydir} || { log_e "failed"; return 1; }
    cmd_run chown 0 ${_lo_emptydir} || { log_e "failed"; return 1; }
    cmd_run chmod 0755 ${_lo_emptydir} || { log_e "failed"; return 1; }
  fi

  cmd_run start-stop-daemon -p ${_pri_daemin_pid} -x ${_pri_daemin_exec} -S
}

sshd_stop () {
  cmd_run start-stop-daemon -p ${_pri_daemin_pid} -K -oq
}

case "$1" in
start)
  shift
  sshd_start
  ;;
stop)
  shift
  sshd_stop
  ;;
restart)
  shift
  $0 stop
  sleep 1
  $0 start "$@"
  ;;
*)
  cat <<-EOHERE
USAGE
    `basename $0` [start|stop|restart]

OPTIONS
    start  Start service
    stop   Stop service

EOHERE
  ;;
esac
