#!/bin/sh

. /etc/init.d/func

check_macaddr () {
  local macaddr="$(get_inient1 $macaddr_cfg macaddr)"
  [ -z "$macaddr" ] || return 0
  
  # local mac bit1 is 1
  macaddr="06:$(hex_gen 5 :)"
  echo "macaddr=$macaddr" > $macaddr_cfg
}

check_serialnum () {
  local serialnum="$(get_inient1 $serialnum_cfg serialnum)"
  [ -z "$serialnum" ] || return 0

  serialnum="$(get_inient1 $macaddr_cfg macaddr | sed -e "s/://g")"
  if [ -n "$serialnum" ]; then
    echo "serialnum=$serialnum" > $serialnum_cfg
    return
  fi
  
  echo "serialnum=$(hex_gen 6)" > $serialnum_cfg  
}

check_refactory () {
  [ -f $oob_cfg ] || return 0
  local refact="$(as_num $(get_inient1 $oob_cfg refactory))"
  if [ "$refact" -ge 1 ] &>/dev/null; then
    log_d "set refactory=$(( $refact - 1 ))"
    echo "refactory=$(( $refact - 1 ))" > $oob_cfg
    return
  fi
  cmd_run rm -rf $oob_cfg
}

check_promisc () {
  [ -f $promisc_cfg ] || return 0
  local promisc="$(as_num $(get_inient1 $promisc_cfg promisc))"
  if [ "$promisc" -ge 1 ] &>/dev/null; then
    log_d "set promisc=$(( $promisc - 1 ))"
    echo "promisc=$(( $promisc - 1 ))" > $promisc_cfg
    return
  fi
  cmd_run rm -rf $promisc_cfg
}

/etc/init.d/mdev-initd start

# cmd_run dmesg -n 4
cmd_run ifconfig lo up 127.0.0.1

# cmd_run /etc/init.d/persist start ||
#   cmd_run /etc/init.d/persist stop

# check_macaddr
# check_serialnum

# [ -f "$hostname_cfg" ] || cmd_run cp /etc/hostname-template "$hostname_cfg"
# cmd_run admin --hostname -f "$hostname_cfg"
hostname -F /etc/hostname-template

# [ -f $wpasup_cfg ] || cmd_run cp /etc/wpa_supplicant-template.conf $wpasup_cfg

# check_refactory
# check_promisc

for script in $(find /etc/init.d -iname "S[0-9]*" | sort); do
  [ -x "$script" ] || continue;
  log_sd "Starting ... $script"
  $script start
done
