#!/bin/sh

. /etc/init.d/func

_pri_tag="syslogd-initd"

log_d "$0 $*"

SYSLOGD_DAEMON=/sbin/syslogd
SYSLOGD_PIDFILE="/var/run/syslogd.pid"
SYSLOGD_CONF="/tmp/syslog.conf"
SYSLOGD_ROTATECNT=5
SYSLOGD_SHM=800
SYSLOGD_ARGS="-L ${SYSLOGD_SHM:+-C${SYSLOGD_SHM}} ${SYSLOGD_ROTATECNT:+-b${SYSLOGD_ROTATECNT}} ${SYSLOGD_CONF:+-f${SYSLOGD_CONF}}"

KLOGD_DAEMON=/sbin/klogd
KLOGD_PIDFILE="/var/run/klogd.pid"
KLOGD_ARGS=

TZFILE="/etc/TZ"

tz_start () {
  if [ -f "$TZFILE" ]; then
    TZ="$(cat $TZFILE)"
    export TZ
  fi
}

syslogd_start () {
  if [ -n "$SYSLOGD_CONF" ] && [ ! -f "$SYSLOGD_CONF" ]; then
    cp /etc/syslog.conf "$SYSLOGD_CONF"
  fi

  cmd_run start-stop-daemon -p $SYSLOGD_PIDFILE -x $SYSLOGD_DAEMON -S -- $SYSLOGD_ARGS
}

syslogd_stop () {
  cmd_run start-stop-daemon -p $SYSLOGD_PIDFILE -K -oq
}

klogd_start () {
  if [ -n "$KLOGD_CONF" ] && [ ! -f "$KLOGD_CONF" ]; then
    cp /etc/syslog.conf "$KLOGD_CONF"
  fi
  cmd_run start-stop-daemon -p $KLOGD_PIDFILE -x $KLOGD_DAEMON -S -- $KLOGD_ARGS
}

klogd_stop () {
  cmd_run start-stop-daemon -p $KLOGD_PIDFILE -K -oq
}

case "$1" in
start)
  shift
  tz_start
  syslogd_start
  klogd_start
  ;;
stop)
  shift
  klogd_stop
  syslogd_stop
  ;;
restart)
  shift
  $0 stop && $0 start "$@"
  ;;
*)
  cat <<-EOHERE
USAGE
    `basename $0` [start|stop|restart]

OPTIONS
    start  Start service
    stop   Stop service

EOHERE
  ;;
esac
