#!/bin/sh

. /etc/init.d/func

_pri_tag="adk-initd"

log_d "$0 $*"

func_rel || {
  _pri_adk_log="/var/run/adk.log"
}
# [ -f "$_pri_adk_log" ] && rm $_pri_adk_log
# _pri_adk_log=/dev/console
_pri_adk_log=${_pri_adk_log:-/dev/null}
log_f "$_pri_adk_log"
log_f "$_pri_adk_log" "$0 $*"

adk_refactory () {
    cmd_run rm -rf ${persist_cfg}/hap-setupinfo /root/.HomeKitStore \
      /root/.command.input /root/Diagnostics
    cmd_run tar -zxvf ${persist_cfg}/hap-setupinfo.tar.gz -C ${persist_cfg} && \
      cmd_run ln -sf ${persist_cfg}/hap-setupinfo /root/.HomeKitStore

    cmd_run rm -rf /root/.airplaydemo ${persist_cfg}/airplaypref
    cmd_run mkdir -p ${persist_cfg}/airplaypref && \
      cmd_run ln -sf ${persist_cfg}/airplaypref /root/.airplaydemo
}

adk_check_cfg () {
  if [ ! -f /root/.HomeKitStore/40.10 ]; then
    if [ -f ${persist_cfg}/hap-setupinfo/40.10 ] && \
        [ -f ${persist_cfg}/airplaypref/airplaydemo.plist ]; then
      log_d "Recover adk keystore"
      cmd_run rm -rf /root/.HomeKitStore && \
        cmd_run ln -sf ${persist_cfg}/hap-setupinfo /root/.HomeKitStore
      cmd_run rm -rf /root/.airplaydemo && \
        cmd_run ln -sf ${persist_cfg}/airplaypref /root/.airplaydemo
    else
      cmd_run adk_refactory
    fi
  fi
  sync; sync
}

case "$1" in
start)
  shift
  pgrep -x ".*adk" &>/dev/null && { log_d "Already running"; exit 0; }
  adk_check_cfg
  cd /root && { eval "adk ${_pri_adk_log:+>>$_pri_adk_log 2>&1} &"; }
  ;;
manual)
  shift
  pgrep -x ".*adk" &>/dev/null && { log_d "Already running"; exit 0; }
  adk_check_cfg
  cd /root && { eval "adk &>/dev/console &"; }
  ;;
stop)
  cmd_run eval "killall -sigint adk mdnsd &>/dev/null"
  _lo_tmo=5
  while [ "$_lo_tmo" -gt 0 ]; do
    log_d "wait adk stop"
    sleep 1
    pgrep -x ".*adk" &>/dev/null || { log_d "adk stop gracefully"; exit 0; }
    _lo_tmo=$(( $_lo_tmo - 1 ))
  done
  ;;
refactory)
  cmd_run adk_refactory
  ;;
restart)
  shift
  cmd_run $0 stop
  pgrep -x ".*adk" &>/dev/null && { log_e "adk not stop"; exit 1; }
  cmd_run $0 start "$@"
  ;;
*)
  cat <<-EOHERE
USAGE
    `basename $0` [start | stop]

OPTIONS
    start  Start service
    stop   Stop service

EOHERE
  ;;
esac
