#!/bin/sh

. /etc/init.d/func

_pri_tag="airplay-initd"

log_d "$0 $*"

_pri_airplay_log="/var/run/airplay.log"
_pri_airplay_exec="/sbin/airplaydemo"
_pri_airplay_lock="/var/run/airplay-initd.lock"
log_f "$_pri_airplay_log"
log_f "$_pri_airplay_log" "$0 $*"

_pri_spklatency=0
_pri_accname="air192"

check_spklatency () {
  log_d "check_spklatency() $*"

  local spklatency="$(as_num $(head -n 50 $spkcal_cfg 2>/dev/null))"
  if [ -z "$spklatency" ] || [ "$spklatency" -lt 0 ]; then
    log_d "No spklatency"
    return 0
  fi
  spklatency="$(spkcal $spklatency 2>/dev/null)"
  if [ -z "$spklatency" ]; then
    log_d "No spklatency"
    return 0
  fi
  local spklatency_min=-5000
  local spklatency_max=5000
  if [ "$spklatency" -lt $spklatency_min ]; then
    log_e "spklantency $spklatency < $spklatency_min"
    spklatency=$spklatency_min
  elif [ "$spklatency" -gt $spklatency_max ]; then
    log_e "spklantency $spklatency > $spklatency_max"
    spklatency=$spklatency_max
  fi
  
  log_d "spklatency $spklatency ms"
  echo $spklatency
}

check_accname () {
  local nm=
  nm=$(head -n 1 $accname_cfg 2>/dev/null)
  [ -n "$nm" ] && echo $nm && return 0

  nm=$(head -n 1 $hostname_cfg 2>/dev/null)
  [ -n "$nm" ] && echo $nm && return 0

  nm=$(head -n 1 /etc/hostname-template 2>/dev/null)
  [ -n "$nm" ] && echo $nm && return 0

  echo "air192"
}

case "$1" in
start)
  shift
  pgrep -x ".*$(basename $_pri_airplay_exec)" &>/dev/null && { log_d "airplay already running"; exit 0; }
  /etc/init.d/mdnsd-initd start
  cmd_run eval "echo -n | aplay -t raw -f S16_LE &>/dev/null"
  cmd_run eval "amixer -c sound1 sset Master 100% >/dev/null"
  _pri_spklatency=`check_spklatency`
  [ -z "$_pri_spklatency" ] || _pri_spklatency=$(( $_pri_spklatency * 1000000 ))

  _pri_accname="`check_accname`"

  cmd_run eval "flock -n $_pri_airplay_lock $_pri_airplay_exec ${_pri_accname:+-n \"${_pri_accname}\"} ${_pri_spklatency:+-d ${_pri_spklatency}} $@ &>$_pri_airplay_log &"
  # return true since might flock but already running
  pgrep -x ".*$(basename $_pri_airplay_exec)" &>/dev/null
  ;;
stop)
  _pri_airplay_pid="$(pgrep -x ".*$(basename $_pri_airplay_exec)")"
  [ -n "$_pri_airplay_pid" ] || exit 0
  log_d "Kill airplay"
  cmd_run eval "kill -9 $_pri_airplay_pid &>/dev/null"
  ;;
restart)
  shift
  $0 stop && $0 start "$@"
  ;;
*)
  cat <<-EOHERE
USAGE
    `basename $0` [start | stop]

OPTIONS
    start  Start service
    stop   Stop service

EOHERE
  ;;
esac
