#!/bin/sh

. /etc/init.d/func

_pri_tag="cputemp-initd"

log_d "$0 $*"

_lo_cputemp_ko="k3_j72xx_bandgap"

cputemp_start () {
  for ko in $_lo_cputemp_ko; do
    cmd_run modprobe $ko || { echo "Failure modprobe $ko"; return 1; }
  done
}

cputemp_stop () {
    for ko in $(echo $_lo_cputemp_ko | tr -s " " "\n" | tac); do
    cmd_run modprobe -r $ko || { echo "Failure modprobe $ko"; return 1; }
  done
}

case "$1" in
"start")
  cmd_run cputemp_start
  ;;
"stop")
  cmd_run cputemp_stop
  ;;
"restart")
  $0 stop && $0 start
  ;;
*)
  cat <<-EOHERE
USAGE
    $(basename "$0") [start | stop]

OPTIONS
    start  Start service
    stop   Stop service

EOHERE
  ;;
esac
