#!/bin/sh

. /etc/init.d/func

_pri_tag="imx219-initd"

log_d "$0 $*"

_lo_imx219_ko="cdns-dphy-rx j721e-csi2rx imx219"

imx219_start() {
  for ko in $_lo_imx219_ko; do
    cmd_run do_modprobe $ko || { echo "Failure modprobe $ko"; return 1; }
  done
}

imx219_stop() {
  for ko in $(echo $_lo_imx219_ko | tr -s " " "\n" | tac); do
    cmd_run modprobe -r $ko || { echo "Failure modprobe $ko"; return 1; }
  done
}

case "$1" in
start)
  cmd_run imx219_start "$@"
  ;;
stop)
  cmd_run imx219_stop
  ;;
"restart")
  shift
  $0 stop
  sleep 1
  $0 start "$@"
  ;;
*)
  cat <<-EOHERE
USAGE
    $(basename "$0") [start | stop]

OPTIONS
    start  Start service
    stop   Stop service

EOHERE
  ;;
esac
