#!/bin/sh

. /etc/init.d/func

_pri_tag="mic"

log_d "$0 $*"

_pri_pdmic_vol=120

pdmic_vol () {
  amixer -c pdmic sset Mic $* &>/dev/null && \
    log_d "Ok: amixer -c pdmic sset Mic $*" || \
    log_e "Failed: amixer -c pdmic sset Mic $*"
}

case "$1" in
"start")
  pdmic_vol $_pri_pdmic_vol
  ;;
"stop")
  ;;
*)
  cat <<-EOHERE
USAGE
    `basename $0` [start | stop]

OPTIONS
    start  Start service
    stop   Stop service

EOHERE
  ;;
esac
