#!/bin/sh

. /etc/init.d/func

_pri_tag="sysemb-initd"

log_d "$0 $*"

_pri_eth0=eth0

ifce_start () {
  [ $# -ge 1 ] || { log_e "Invalid argument"; return 1; }
  _lo_ifce=$1
  ifconfig "${_lo_ifce}" up
  ifconfig "${_lo_ifce}" 192.168.16.26
}

case "$1" in
"start")
  cmd_run ifce_start ${_pri_eth0}
  ;;
"stop")
  cmd_run ifce_down1 ${_pri_eth0}
  ;;
"restart")
  $0 stop && $0 start
  ;;
*)
  cat <<-EOHERE
USAGE
    `basename $0` [start | stop]

OPTIONS
    start  Start service
    stop   Stop service

EOHERE
  ;;
esac
