#!/bin/sh

. /etc/init.d/func

_pri_tag="restmon"

log_d "$0 $*"

# _pri_restmon_log="/var/run/restmon.log"
# [ -f "$_pri_restmon_log" ] && rm $_pri_restmon_log

_pri_restmon_log=${_pri_restmon_log:-/dev/null}
log_f "$_pri_restmon_log"
log_f "$_pri_restmon_log" "$0 $*"

case "$1" in
start)
  _pri_cmd="admin --ctrlport=/root/admin-ctrl --restkey=120 --restdur=10"
  if [ -f "$led_cfg" ]; then
    _pri_cmd="$_pri_cmd --ledconf=$led_cfg"
  fi
  cmd_run eval "$_pri_cmd ${_pri_restmon_log:+-vvv >>$_pri_restmon_log 2>&1} &"
  exit
  ;;
stop)
  pgrep -x ".*admin" &>/dev/null || exit 0
  killall admin &>/dev/null
  exit
  ;;
restart)
  shift
  $0 stop && $0 start "$@"
  ;;
*)
  cat <<-EOHERE
USAGE
    `basename $0` [start | stop]

OPTIONS
    start  Start service
    stop   Stop service

EOHERE
esac
