#!/bin/sh

. /etc/init.d/func

_pri_tag="sysemb-initd"

log_d "$0 $*"

_pri_eth0=eth0

case "$1" in
"start")
  ifce_reset1 ${_pri_eth0}
  ;;
"stop")
  ifce_down1 ${_pri_eth0}
  ;;
"restart")
  $0 stop && $0 start
  ;;
*)
  cat <<-EOHERE
USAGE
    `basename $0` [start | stop]

OPTIONS
    start  Start service
    stop   Stop service

EOHERE
  ;;
esac
