#!/bin/sh

. /etc/init.d/func

_pri_tag="tidss-initd"

log_d "$0 $*"

_lo_tidss_ko="fb display-connector ite-it66121 tidss"

tidss_start () {
  for ko in $_lo_tidss_ko; do
    cmd_run modprobe $ko || { echo "Failure modprobe $ko"; return 1; }
  done
}

tidss_stop () {
    for ko in $(echo $_lo_tidss_ko | tr -s " " "\n" | tac); do
    cmd_run modprobe -r $ko || { echo "Failure modprobe $ko"; return 1; }
  done
}

case "$1" in
"start")
  cmd_run tidss_start
  ;;
"stop")
  cmd_run tidss_stop
  ;;
"restart")
  $0 stop && $0 start
  ;;
*)
  cat <<-EOHERE
USAGE
    $(basename "$0") [start | stop]

OPTIONS
    start  Start service
    stop   Stop service

EOHERE
  ;;
esac
