#!/bin/sh

. /etc/init.d/func

_pri_tag="wifi"

log_d "$0 $*"

_pri_regdom=TW
_pri_sddev=

_pri_dexatek_oui="3c:6a:9d"

sdhci () {
  [ -e "/sys/module/sdhci_of_at91" ] && { log_d "module already loaded: sdhci_of_at91"; return 0; }
  local ko_root="/lib/modules/`uname -r`/kernel"
  local sdhci=`find ${ko_root} -iname sdhci-of-at91.ko`
  do_insmod ${sdhci} ${sdhci_args} && sleep 0.5 || return 1
}

wifi_stop () {
  for i in brcmfmac brcmutil 8821cs; do
    [ ! -e /sys/module/$i ] || cmd_run rmmod $i
  done
  # for i in mac80211 cfg80211 compat; do
  #   [ ! -e /sys/module/$i ] || cmd_run rmmod $i
  # done
}

promisc_on () {
  local wphy="`wphy_wait`" || { log_se "missing wphy"; return 1; }
  local wlan=wlan${wphy##phy}
  cmd_run ip link set $wlan promisc on
}

brcm () {
  local cfg80211_args="${_pri_regdom:+ieee80211_regdom=$_pri_regdom}"
  # local brcmfmac_args="debug=0x100"

  local ko_root="/lib/modules/`uname -r`"

  local fmac_root="${ko_root}/updates"
  local brcmfmac="`find ${fmac_root} -iname brcmfmac.ko`"
  if [ ! -e ${brcmfmac} ]; then
    # might linux upstream
    fmac_root="${ko_root}/kernel"
    brcmfmac="`find ${fmac_root} -iname brcmfmac.ko`"
  fi
  [ -e "${brcmfmac}" ] || { log_e "missing brcmfmac.ko"; return 1; }

  local brcmutil="`find ${fmac_root} -iname brcmutil.ko`"
  [ -e "${brcmutil}" ] || { log_e "missing brcmutil.ko"; return 1; }

  local cfg80211=`find ${fmac_root} -iname cfg80211.ko`
  [ -e "${cfg80211}" ] || { log_e "missing cfg80211.ko"; return 1; }

  # optional
  local compat="`find ${fmac_root} -iname compat.ko`"
  local mac80211=`find ${fmac_root} -iname mac80211.ko`

  if [ -e "${compat}" ]; then
    do_insmod ${compat} || return 1
  else
    log_d "module ignore: compat.ko"
  fi

  do_insmod ${cfg80211} ${cfg80211_args} || return 1

  if [ -e "${mac80211}" ]; then
    do_insmod ${mac80211} || return 1
  else
    log_d "module ignore: mac80211.ko"
  fi

  sdhci || return 1
  do_insmod ${brcmutil} || return 1
  do_insmod ${brcmfmac} ${brcmfmac_args} || return 1
}

# ch: 0x42 (support only 36, 40, 44, 48), 0x80 (full)
rtl8821_chanplan_def=0x80

rtl8821_chanplan_set () {
  local ch=${1:-$rtl8821_chanplan_def}
  local ct=${2:-5}

  local wphy="`wphy_wait`" || { log_se "missing wphy"; return 1; }
  local wlan=wlan${wphy##phy}
  echo $ch > /proc/net/rtl8821cs/${wlan}/chan_plan

  local ch_r=$(cat /proc/net/rtl8821cs/wlan0/chan_plan | sed -E -n "s/chplan:([0-9a-fA-FxX]*)/\1/p")
  log_d "set channel plan: $ch_r"
}

rtl8821_ps () {
  local mode=$1
  local wphy="`wphy_wait`" || { log_se "missing wphy"; return 1; }
  local wlan=wlan${wphy##phy}

  case $mode in
  1)
    # cmd_run iwpriv $wlan pm_set ips=1
    cmd_run iwpriv $wlan pm_set lps=1
    ;;
  *)
    # cmd_run iwpriv $wlan pm_set ips=0
    cmd_run iwpriv $wlan pm_set lps=0
    ;;
  esac
}

rtl8821 () {
  local cfg80211_args="${_pri_regdom:+ieee80211_regdom=$_pri_regdom}"
  local rtl8821_args="rtw_drv_log_level=3"

  _pri_wfatest="$(as_num $(get_inient1 $wfa_cfg wfa_test))"
  if [ "$_pri_wfatest" -ge 1 ] &>/dev/null; then
    rtl8821_args="${rtl8821_args:+$rtl8821_args }rtw_wifi_spec=1"
  fi

  local ko_root="/lib/modules/`uname -r`"

  local rtl8821_root="${ko_root}/extra"
  local rtl8821="`find ${rtl8821_root} -iname 8821cs.ko`"
  if [ ! -e ${rtl8821} ]; then
    # might linux upstream
    rtl8821_root="${ko_root}/kernel"
    rtl8821="`find ${rtl8821_root} -iname 8821cs.ko`"
  fi
  [ -e "${rtl8821}" ] || { log_e "missing 8821cs.ko"; return 1; }

  local cfg80211=`find ${ko_root}/kernel -iname cfg80211.ko`
  [ -e "${cfg80211}" ] || { log_e "missing cfg80211.ko"; return 1; }

  # optional
  # local compat="`find ${fmac_root} -iname compat.ko`"
  # local mac80211=`find ${fmac_root} -iname mac80211.ko`

  # if [ -e "${compat}" ]; then
  #   do_insmod ${compat} || return 1
  # else
  #   log_d "module ignore: compat.ko"
  # fi

  do_insmod ${cfg80211} ${cfg80211_args} || return 1

  sdhci || return 1
  do_insmod ${rtl8821} ${rtl8821_args} || return 1

  rtl8821_chanplan_set || return 1
  rtl8821_ps || return 1

  local promisc="$(as_num $(get_inient1 $promisc_cfg promisc))"
  [ "$promisc" -ge 1 ] &>/dev/null && promisc_on || return 0
}

set_wifi_mac() {
  local wifi_macaddr="$(norm_macaddr "$(get_inient1 "$wifi_macaddr_cfg" macaddr)" ":")"
  if [ -z "$wifi_macaddr" ]; then
    # wifi_macaddr="${_pri_dexatek_oui}:$(hex_gen 3)"
    # echo "macaddr=$wifi_macaddr" > $wifi_macaddr_cfg
    # log_sd "generate $(cat $wifi_macaddr_cfg)"
    return 1
  fi
  sleep 0.5
  ip l set wlan0 up address $wifi_macaddr  
}

case "$1" in
"start")
  sdhci || exit

  _pri_dev="`find_sddev $sd_rtl_vid $sd_rtl8821_did`"
  if [ -n "$_pri_dev" ]; then
    log_d "found rtl8821 at $_pri_dev"
    rtl8821
    set_wifi_mac
    exit
  fi

  _pri_dev="`find_sddev $sd_brcm_vid $sd_brcm43455_did`"
  if [ -n "$_pri_dev" ]; then
    log_d "found brcm43455 at $_pri_dev"
    brcm
    exit
  fi

  _pri_dev="`find_sddev $sd_brcm_vid $sd_brcm43438_did`"
  if [ -n "$_pri_dev" ]; then
    log_d "found brcm43438 at $_pri_dev"
    brcm
    exit
  fi

  log_se "miss wifi device"
  false
  ;;
"brcm")
  brcm
  ;;
"rtl8821")
  rtl8821
  ;;
"stop")
  wifi_stop
  ;;
"restart")
  $0 stop && $0 start
  ;;
*)
  cat <<-EOHERE
USAGE
    `basename $0` [start | stop]

OPTIONS
    start  Start service
    stop   Stop service

EOHERE
  ;;
esac
