#!/bin/sh

. /etc/init.d/func

_pri_tag="ifplugd-default"

log_d "$0 $*"

ifce=$1
act=$2

if [ -f "$mainguard_cfg" ]; then
  log_d "Found $mainguard_cfg"
  found_mainguard=1
else
  found_mainguard=
fi

case $ifce in
eth*)
  if ifce_link_up $ifce; then
    log_d "Expect ifup for $ifce"
  elif [ "$act" == "up" ]; then
    log_e "$ifce link state actually down"
  fi
  if [ "$act" == "down" ]; then
    log_d "Expect ifdown for $ifce"
  fi
  exit
  ;;
wlan*)
  ;;
*)
  ;;
esac
