set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(TARGET_TRIPLE aarch64-linux-gnu)

set(GCC_SYSROOT 
    "$${GCC_SYSROOT}")

set(BP_SYSROOT
    "$${BP_SYSROOT}")

set(CMAKE_C_COMPILER
    "$${CC}")

set(CMAKE_CXX_COMPILER
    "$${CXX}")

set(CMAKE_C_COMPILER_TARGET aarch64-linux-gnu)
set(CMAKE_CXX_COMPILER_TARGET aarch64-linux-gnu)

set(CMAKE_SYSROOT "${GCC_SYSROOT}")

set(CMAKE_C_FLAGS
    "-I${BP_SYSROOT}/include")

set(CMAKE_CXX_FLAGS
    "-I${BP_SYSROOT}/include")

set(CMAKE_EXE_LINKER_FLAGS
    "-L${BP_SYSROOT}/lib")

set(CMAKE_SHARED_LINKER_FLAGS
    "-L${BP_SYSROOT}/lib")

set(CMAKE_FIND_ROOT_PATH
    "${BP_SYSROOT}"
    "${GCC_SYSROOT}"
)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
